---
- hosts: localhost
  gather_facts: False
 
  tasks:
   - name: Detach volume
     ec2_vol:
        id: vol-0a88f124109998314
        region: us-east-1
        instance: None
        state: absent
