---
- hosts: localhost
  gather_facts: False
 
  tasks:
   - name: Detach first volume
     ec2_vol:
        id: "{{vol_id1}}"
        region: us-east-1
        instance: None
      
   - name: Delete first volume 
     ec2_vol:
        id: "{{vol_id1}}"
        region: us-east-1
        state: absent
      
   - name: Detach second volume
     ec2_vol:
        id: "{{vol_id2}}"
        region: us-east-1
        instance: None
        
   - name: Delete second volume 
     ec2_vol:
        id: "{{vol_id2}}"
        region: us-east-1
        state: absent
