---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
  tasks:
    - name: Create or resize a volume group on top of /dev/xvdf and /dev/xvdg
      lvg:
          vg: "{{vg_name}}"
          pvs: /dev/xvdf,/dev/xvdg

    - name: Create a logical volume of with disks /dev/sda and /dev/sdb
      lvol:
          vg: "{{vg_name}}"
          lv: "{{lv_name}}"
          size: "{{vol_size}}"
          pvs: /dev/xvdf,/dev/xvdg

    - name: Create Directory
      file:
          path: "{{directoy_path}}"
          state: directory

    - name: create file system
      filesystem:
          fstype: ext4
          dev: /dev/{{vg_name}}/{{lv_name}}

    - name: mount logical volume
      mount:
           name: "{{directoy_path}}"
           src: /dev/{{vg_name}}/{{lv_name}}
           fstype: ext4
           state: present
