---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
  vars:
       vg_name: test-lvm
       lv_name: new-vol1
  tasks:
    - name: create file system
      filesystem:
          fstype: ext3
          dev: /dev/{{vg_name}}/{{lv_name}}

    - name: mount logical volume
      mount:
           name: /mnt/lvm1
           src: /dev/{{vg_name}}/{{lv_name}}
           fstype: ext3
           state: present
