---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
  tasks:
    - name: Remove the logical volume.
      lvol:
           vg: test-lvm
           lv: new-vol1
        state: absent
        force: yes
