---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
  tasks:
    - name: unmount logical volume
      mount:
           name: "{{dir_path}}"
           src: /dev/{{vg_name}}/{{lv_name}}
           fstype: ext3
           state: absent
    - file:
           path: "{{dir_path}}"
           state: directory
           state: absent
           
    
    - name: Deactivate a logical volume
      lvol:
           vg: "{{vg_name}}"
           lv: "{{lv_name}}"
           active: false
           
    - name: Remove the logical volume.
      lvol:
           vg: "{{vg_name}}"
           lv: "{{lv_name}}"
           state: absent
           force: yes
           
    - name: Remove the volume group.
      lvg:
        vg: "{{vg_name}}"
        state: absent

    - name: Remove the PV volume group.
      shell: pvremove /dev/xvdf /dev/xvdg
