---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
  tasks:
    - name: remove directory
      shell: rm -rf /mnt/lvm
    
    - name: Deactivate a logical volume
      lvol:
           vg: test-lvm
           lv: new-vol1
           active: false
           
    - name: Remove the logical volume.
      lvol:
           vg: test-lvm
           lv: new-vol1
           state: absent
           force: yes
           
    - name: Remove the volume group.
      lvg:
        vg: test-lvm
        state: absent

    - name: Remove the PV volume group.
      shell: pvremove /dev/xvdf /dev/xvdg
