---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
 
  tasks:
    - name: Create Directory
      file:
           path: /mnt/lvm1
           state: directory
    - name: create file system
      filesystem:
           fstype: ext3
           dev: /dev/test-lvm/new-vol1
    - name: mount logical volume
      mount:
           name: /mnt/lvm1
           src: /dev/test-lvm/new-vol1
