---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
 
  tasks:
    
    - name: Create or resize a volume group on top of /dev/xvdf and /dev/xvdg
      lvg:
           vg: test-lvm
           pvs: /dev/xvdf,/dev/xvdg
           state: present
    - name: Create a logical volume of 512m with disks /dev/sda and /dev/sdb
      lvol:
           vg: test-lvm
           lv: new-vol1
           size: 512
           pvs: /dev/xvdf,/dev/xvdg
           state: present
    - name: Create Directory
      file:
           path: /mnt/lvm1
           state: directory
           state: present
    - name: create file system
      filesystem:
           fstype: ext3
           dev: /dev/test-lvm/new-vol1
           state: present
    - name: mount logical volume
      mount:
           name: /mnt/lvm1
           src: /dev/test-lvm/new-vol1
           state: present
