---
- hosts: 172.31.7.165
  become: yes
  become_method: sudo
 
  tasks:           
    - name: mount logical volume
      mount:
           name: /mnt/lvm1
           src: /dev/test-lvm/new-vol1
           fstype: ext3
           state: present
