---
- hosts: All
  become: yes
  become_method: sudo
  
  tasks:
    - name: Set authorized keys taken from url
      authorized_key:
                user: charlie
                state: present
                key: https://github.com/nakulbarai.keys

