---
- hosts: 10.243.101.191
  gather_facts: False
  
  tasks:
    - name: Set authorized keys taken from url
      authorized_key:
                user: charlie
                state: present
                key: https://github.com/nakulbarai.keys

