---
- name: control remote legacy system
  hosts: legacy
  gather_facts: no

  tasks:
  - name: create script on the fly to manage system
    template:
      src: /var/tmp/telegraf-1.5.3-1.x86_64.rpm
      dest: "/var/tmp/telegraf-1.5.3-1.x86_64.rpm”
    delegate_to: localhost
 
  - name: execute raw command to upgrade system
    raw:
      rpm -Uvh /var/tmp/telegraf-1.5.3-1.x86_64.rpm
