---
- hosts: all
  gather_facts: False
  
  tasks:  
  - name: local scp
    local_action: command sudo scp /var/tmp/telegraf-1.5.3-1.x86_64.rpm {{ inventory_hostname }}:/var/tmp/telegraf-1.5.3-1.x86_64.rpm
