---
- hosts: all
  become: yes
  gather_facts: False
  
  tasks:  
  - name: local scp
    raw: command scp /var/tmp/telegraf-1.5.3-1.x86_64.rpm tivo@{{ inventory_hostname }}:/var/tmp/telegraf-1.5.3-1.x86_64.rpm
    become: true
