---
- hosts: all
  no_log: True
  remote_user: tivo
  become: yes
  become_method: su
    tasks:
      - name: Copy telegraf package to remote server
        copy:
         src: telegraf-1.5.3-1.x86_64.rpm
         dest: /var/tmp/telegraf-1.5.3-1.x86_64.rpm

      - name: install telegraf from local file
           yum:
             name: /var/tmp/telegraf-1.5.3-1.x86_64.rpm
             disable_gpg_check: yes
             state: present
